# ONLY FOR DEVELOPMENT PURPOSES. The cmdlet reference website is not hosted on
# App Engine.
#
# This app.yaml is the simplest way to replicate running the website on GitHub
# Pages. When published, the root of the website will be:
# googlecloudplatform.github.io/google-cloud-powershell/
#
# So when running a typical webserver, index.html would assume it is at the
# root of the domain. The app.yaml file does the schenanigans for URL handling
# so that localhost:8080/google-cloud-powershell/ loads the right file.
application: do-not-deploy-this-app
version: do-not-deploy-this-app
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Render files under /google-cloud-powershell/ as if they were in / 
- url: /google-cloud-powershell/(.*\.(js|json|css|html|png|ng))
  static_files: \1
  upload: .*

# Special case since the devappserver won't automatically return index.html.
- url: /google-cloud-powershell/
  static_files: index.html
  upload: index.html

# Should not be reachable when hosted on GitHub Pages.
- url: /
  static_files: dev-redirect.html
  upload: dev-redirect.html